groups:
- name: metamonitoring
  rules:
  - alert: PrometheusReplicaDown
    annotations:
      message: Prometheus replica in cluster {{$labels.cluster}} has disappeared from Prometheus target discovery.
    expr: |
      label_replace(
        absent(sum(up{job="prometheus", cluster="hanhnn", instance=~".*:9090"}) by (job, cluster) == 2),
        "cluster", "hanhnn", "",""
      )
      #or
      #label_replace(
      #  absent(sum(up{job="prometheus", cluster="seattle", instance=~".*:9090"}) by (job, cluster) == 2),
      #  "cluster", "seattle", "",""
      #)
    for: 15s # for demo purposes
    labels:
      severity: critical
